/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class depan extends javax.swing.JFrame {

    /**
     * Creates new form depan
     */
    public depan() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tb_regist = new javax.swing.JButton();
        tb_data = new javax.swing.JButton();
        tb_daf = new javax.swing.JButton();
        tb_hstry = new javax.swing.JButton();
        btnLogin = new javax.swing.JLabel();
        koleksiBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_regist.setBackground(new java.awt.Color(255, 153, 102));
        tb_regist.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        tb_regist.setForeground(new java.awt.Color(255, 255, 255));
        tb_regist.setText("REGISTER");
        tb_regist.setBorder(null);
        tb_regist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_registActionPerformed(evt);
            }
        });
        jPanel1.add(tb_regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 140, 40));

        tb_data.setBackground(new java.awt.Color(0, 0, 0));
        tb_data.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tb_data.setForeground(new java.awt.Color(255, 153, 51));
        tb_data.setText("Jurnal Terdaftar");
        tb_data.setBorder(null);
        tb_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_dataActionPerformed(evt);
            }
        });
        jPanel1.add(tb_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 200, 50));

        tb_daf.setBackground(new java.awt.Color(0, 0, 0));
        tb_daf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tb_daf.setForeground(new java.awt.Color(255, 153, 51));
        tb_daf.setText("Daftarkan Jurnal");
        tb_daf.setBorder(null);
        tb_daf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_daf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_dafActionPerformed(evt);
            }
        });
        jPanel1.add(tb_daf, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, 50));

        tb_hstry.setBackground(new java.awt.Color(0, 0, 0));
        tb_hstry.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tb_hstry.setForeground(new java.awt.Color(255, 153, 51));
        tb_hstry.setText("History ");
        tb_hstry.setBorder(null);
        tb_hstry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_hstry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hstryActionPerformed(evt);
            }
        });
        jPanel1.add(tb_hstry, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 200, 50));

        btnLogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 153, 102));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 110, 40));

        koleksiBtn.setBackground(new java.awt.Color(0, 0, 0));
        koleksiBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        koleksiBtn.setForeground(new java.awt.Color(255, 153, 51));
        koleksiBtn.setText("Koleksiku");
        koleksiBtn.setBorder(null);
        koleksiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        koleksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koleksiBtnActionPerformed(evt);
            }
        });
        jPanel1.add(koleksiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 200, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("EXIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/front.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_registActionPerformed
        // TODO add your handling code here:
        this.dispose();
        register a = new register();
        a.setVisible(true);
    }//GEN-LAST:event_tb_registActionPerformed

    private void tb_dafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_dafActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Anda belum memiliki akun!\nSilakan registrasi terlebih dahulu.");
    }//GEN-LAST:event_tb_dafActionPerformed

    private void tb_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_dataActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Anda belum memiliki akun!\nSilakan registrasi terlebih dahulu.");

    }//GEN-LAST:event_tb_dataActionPerformed

    private void tb_hstryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hstryActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Anda belum memiliki akun!\nSilakan registrasi terlebih dahulu.");

    }//GEN-LAST:event_tb_hstryActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        this.dispose();
        login a = new login();
        a.setVisible(true);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void koleksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koleksiBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Anda belum memiliki akun!\nSilakan registrasi terlebih dahulu.");
    }//GEN-LAST:event_koleksiBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new depan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton koleksiBtn;
    private javax.swing.JButton tb_daf;
    private javax.swing.JButton tb_data;
    private javax.swing.JButton tb_hstry;
    private javax.swing.JButton tb_regist;
    // End of variables declaration//GEN-END:variables
}
