/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class history extends javax.swing.JFrame {

    private history() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
   
    private void clearForm() {
        txtPg.setText("");
        txtJud.setText("");
        txtThn.setText("");
        txtPnb.setText("");
        txtTp.setText("");
    }

    /**
     * Creates new form history
     */
    public history(String user) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        txtName.setText(user);
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "select id from register where user ='"+txtName.getText()+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            if (rs.next()) {
                idTxt.setText(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(masuk.class.getName()).log(Level.SEVERE, null, ex);
        }
        Fetch1();
        LoadNoJurnal();
    }

    private void Fetch1() {
        int q;
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT * FROM data_jurnal WHERE user_id ='"+idTxt.getText()+"';";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            q = res.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) table2.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= q; a++) {
                    v2.add(rs.getString("no_jurnal"));
                    v2.add(rs.getString("pengarang"));
                    v2.add(rs.getString("judul"));
                    v2.add(rs.getString("tahun"));
                    v2.add(rs.getString("penerbit"));
                    v2.add(rs.getString("topik"));
                    v2.add(rs.getString("user_id"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(history.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void LoadNoJurnal() {

        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT no_jurnal FROM `data_jurnal` WHERE user_id ='"+idTxt.getText()+"';";
            PreparedStatement s = conn.prepareStatement(sql);
            ResultSet rs = s.executeQuery();
            boxNo.removeAllItems();
            while (rs.next()) {
                boxNo.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(history.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        txtPg = new javax.swing.JTextField();
        txtJud = new javax.swing.JTextField();
        txtThn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPnb = new javax.swing.JTextField();
        txtTp = new javax.swing.JTextField();
        boxNo = new javax.swing.JComboBox<>();
        BtnDel = new javax.swing.JButton();
        BtnUpt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        bg = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        txtName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCari.setBackground(new java.awt.Color(51, 51, 51));
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Search");
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));
        jPanel1.add(txtPg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 330, 30));
        jPanel1.add(txtJud, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 330, 30));
        jPanel1.add(txtThn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 330, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back2.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));
        jPanel1.add(txtPnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));
        jPanel1.add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        boxNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari ", " " }));
        jPanel1.add(boxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 220, -1));

        BtnDel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        BtnDel.setForeground(new java.awt.Color(102, 51, 0));
        BtnDel.setText("Delete");
        BtnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 120, -1));

        BtnUpt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        BtnUpt.setForeground(new java.awt.Color(102, 51, 0));
        BtnUpt.setText("Update");
        BtnUpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUptActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 120, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Menu: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        jLabel3.setText("Pengarang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        jLabel4.setText("Judul");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        jLabel5.setText("Penerbit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        jLabel6.setText("Tahun");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        jLabel7.setText("Topik");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        table2.setBackground(new java.awt.Color(204, 204, 204));
        table2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Jurnal", "Pengarang", "Judul", "Tahun", "Penerbit", "Topik"
            }
        ));
        jScrollPane1.setViewportView(table2);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(0).setPreferredWidth(67);
            table2.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 530, 430));

        bg.setBackground(new java.awt.Color(204, 204, 255));
        bg.setForeground(new java.awt.Color(204, 204, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/historyframe.png"))); // NOI18N
        bg.setText(" ");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 70, -1));

        txtName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            // TODO add your handling code here:
            Connection conn = Koneksi.getKoneksi();
            String noJur = boxNo.getSelectedItem().toString();
            String sql = "SELECT * FROM data_jurnal WHERE no_jurnal=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, noJur);
            ResultSet rs = ps.executeQuery();

            if (rs.next() == true) {
                txtPg.setText(rs.getString(2));
                txtJud.setText(rs.getString(3));
                txtThn.setText(rs.getString(4));
                txtPnb.setText(rs.getString(5));
                txtTp.setText(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch (SQLException ex) {
            Logger.getLogger(history.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCariActionPerformed

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        // TODO add your handling code here:
        int question = JOptionPane.showConfirmDialog(null, "Yakin akan menghapus data jurnal ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (question == JOptionPane.OK_OPTION) {
            try {
                Connection conn = Koneksi.getKoneksi();
                String noJur = boxNo.getSelectedItem().toString();
                String sql = "DELETE FROM data_jurnal WHERE no_jurnal=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, noJur);

                int k = ps.executeUpdate();
                if (k == 1) {
                    JOptionPane.showMessageDialog(this, "Data telah dihapus");
                    clearForm();
                    boxNo.requestFocus();
                    LoadNoJurnal();
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus");

                }
            } catch (SQLException ex) {
                Logger.getLogger(history.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (question == JOptionPane.CANCEL_OPTION) {

        }
    }//GEN-LAST:event_BtnDelActionPerformed

    private void BtnUptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUptActionPerformed
        try {
            // TODO add your handling code here:
            Connection c = Koneksi.getKoneksi();
            String prg = txtPg.getText();
            String jdl = txtJud.getText();
            String th = txtThn.getText();
            String pb = txtPnb.getText();
            String top = txtTp.getText();
            String noJur = boxNo.getSelectedItem().toString();
            String sql = "UPDATE data_jurnal SET pengarang=?,judul=?,tahun=?,penerbit=?,topik=? WHERE no_jurnal=?";
            PreparedStatement ps = c.prepareStatement(sql);

            ps.setString(1, prg);
            ps.setString(2, jdl);
            ps.setString(3, th);
            ps.setString(4, pb);
            ps.setString(5, top);
            ps.setString(6, noJur);

            int k = ps.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Data telah berhasil diupdate!");
                clearForm();
                Fetch1();
                boxNo.requestFocus();
                LoadNoJurnal();
            }
        } catch (SQLException ex) {
            Logger.getLogger(history.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnUptActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idTxtActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        masuk a = new masuk(txtName.getText());
        a.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnUpt;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> boxNo;
    private javax.swing.JButton btnCari;
    public javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txtJud;
    public javax.swing.JLabel txtName;
    private javax.swing.JTextField txtPg;
    private javax.swing.JTextField txtPnb;
    private javax.swing.JTextField txtThn;
    private javax.swing.JTextField txtTp;
    // End of variables declaration//GEN-END:variables
}
