/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class koleksiku extends javax.swing.JFrame {

    /**
     * Creates new form koleksiku
     */
    public koleksiku(String nama5) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        namaTxt.setText(nama5);
        loadTopik();
        Fetch();
    }
    
    private void Fetch() {
        DefaultTableModel df = new DefaultTableModel();
        df.addColumn("Nomor");
        df.addColumn("No jurnal");
        df.addColumn("Pengarang");
        df.addColumn("Judul");
        df.addColumn("Tahun");
        df.addColumn("Penerbit");
        df.addColumn("Topik");
        
        try {
            int no = 1;
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT * FROM koleksiku WHERE user ='"+namaTxt.getText()+"' ORDER BY no_jurnal ASC;";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                df.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
            tableKol.setModel(df);
        } catch (SQLException ex) {
            Logger.getLogger(koleksiku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadTopik() {
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT topik FROM koleksiku WHERE user ='"+namaTxt.getText()+"';";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            topikCmb.removeAllItems();
            while(rs.next()) {
                topikCmb.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(koleksiku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private koleksiku() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKol = new javax.swing.JTable();
        delete = new javax.swing.JLabel();
        topikCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JLabel();
        noJurnal = new javax.swing.JTextField();
        pgrg = new javax.swing.JTextField();
        jdl = new javax.swing.JTextField();
        thn = new javax.swing.JTextField();
        pbt = new javax.swing.JTextField();
        top = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableKol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No. Jurnal", "Pengarang", "Judul", "Tahun", "Penerbit", "Topik"
            }
        ));
        tableKol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKol);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 893, 370));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-trash-can-24.png"))); // NOI18N
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 30, 30));

        topikCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknologi", "Sains", "Pendidikan", "Kedokteran", "Ekonomi", "Teknik" }));
        topikCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topikCmbActionPerformed(evt);
            }
        });
        jPanel1.add(topikCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back2.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-reset-24.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 40, 30));

        cari.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cari.setText("Search");
        cari.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1081, 90, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/koleksi.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 610));
        jPanel1.add(namaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        noJurnal.setText("jTextField1");
        jPanel1.add(noJurnal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        pgrg.setText("jTextField2");
        jPanel1.add(pgrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, -1, -1));

        jdl.setText("jTextField3");
        jPanel1.add(jdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 120, -1));

        thn.setText("jTextField4");
        jPanel1.add(thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        pbt.setText("jTextField5");
        jPanel1.add(pbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        top.setText("jTextField6");
        jPanel1.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableKolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKolMouseClicked
        // TODO add your handling code here:
        int baris = tableKol.rowAtPoint(evt.getPoint());
        String noJr = tableKol.getValueAt(baris, 1).toString();
        noJurnal.setText(noJr);
        String prg = tableKol.getValueAt(baris, 2).toString();
        pgrg.setText(prg);
        String jud = tableKol.getValueAt(baris, 3).toString();
        jdl.setText(jud);
        String thun = tableKol.getValueAt(baris, 4).toString();
        thn.setText(thun);
        String pnr = tableKol.getValueAt(baris, 5).toString();
        pbt.setText(pnr);
        String tpk = tableKol.getValueAt(baris, 6).toString();
        top.setText(tpk);
    }//GEN-LAST:event_tableKolMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        try {
            Connection conn = Koneksi.getKoneksi();
            int jawab = JOptionPane.showOptionDialog(this, "Anda yakin akan menghapus data ini?", "Delete", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (jawab == JOptionPane.OK_OPTION) {
            String sql = "DELETE FROM koleksiku WHERE no_jurnal ='"+noJurnal.getText()+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            }
            Fetch();
        } catch (SQLException ex) {
            Logger.getLogger(koleksiku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor");
        model.addColumn("No Jurnal");
        model.addColumn("Pengarang");
        model.addColumn("Judul");
        model.addColumn("Tahun");
        model.addColumn("Penerbit");
        model.addColumn("Topik");

        try {
            Connection conn = Koneksi.getKoneksi();
            String topik = topikCmb.getSelectedItem().toString();
            String sql = "SELECT * FROM koleksiku WHERE topik=? AND user ='"+namaTxt.getText()+"';";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, topik);
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                });
            }
            tableKol.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(koleksiku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Fetch();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        masuk b = new masuk(namaTxt.getText());
        b.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void topikCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topikCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topikCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koleksiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koleksiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koleksiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koleksiku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koleksiku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cari;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jdl;
    private javax.swing.JLabel namaTxt;
    private javax.swing.JTextField noJurnal;
    private javax.swing.JTextField pbt;
    private javax.swing.JTextField pgrg;
    private javax.swing.JTable tableKol;
    private javax.swing.JTextField thn;
    private javax.swing.JTextField top;
    private javax.swing.JComboBox<String> topikCmb;
    // End of variables declaration//GEN-END:variables
}
