/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.HeadlessException;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class upjurnal extends javax.swing.JFrame {

    private upjurnal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void clearForm() {
        txt_noJurnal.setText(null);
        txt_prg.setText(null);
        txt_jdl.setText(null);
        txt_thn.setText(null);
        txt_pnerbit.setText(null);
        txt_topik.setText(null);
        txtId.setText(null);
        autonumber();
    }

    /**
     * Creates new form upjurnal
     */
    public upjurnal(String nama2) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        txt_noJurnal.setEditable(false);
        autonumber();
        jLabel1.setText(nama2);
    }
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    private void autonumber() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select * from data_jurnal order by no_jurnal desc";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String noJurnal = r.getString("no_jurnal").substring(2);
                String no = "" + (Integer.parseInt(noJurnal) + 1);
                String zero = "";

                if (no.length() == 1) {
                    zero = "00";
                } else if (no.length() == 2) {
                    zero = "0";
                } else if (no.length() == 3) {
                    zero = "";
                }
                txt_noJurnal.setText("J" + zero + no);
            } else {
                txt_noJurnal.setText("J003");
            }
            r.close();
            s.close();

        } catch (Exception e) {
            System.out.println("autonumber error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_noJurnal = new javax.swing.JTextField();
        txt_prg = new javax.swing.JTextField();
        txt_jdl = new javax.swing.JTextField();
        txt_thn = new javax.swing.JTextField();
        txt_topik = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btn_sub = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_pnerbit = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back2.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        txt_noJurnal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_noJurnal.setBorder(new javax.swing.border.MatteBorder(null));
        txt_noJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noJurnalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_noJurnal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 480, 40));

        txt_prg.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt_prg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txt_prg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 480, 40));

        txt_jdl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt_jdl.setBorder(new javax.swing.border.MatteBorder(null));
        txt_jdl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_jdlFocusGained(evt);
            }
        });
        txt_jdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jdlActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 480, 40));

        txt_thn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt_thn.setBorder(new javax.swing.border.MatteBorder(null));
        txt_thn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thnActionPerformed(evt);
            }
        });
        jPanel1.add(txt_thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 480, 40));

        txt_topik.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt_topik.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txt_topik, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 480, 40));

        txtId.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtId.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 480, 40));

        btn_sub.setBackground(new java.awt.Color(255, 255, 255));
        btn_sub.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btn_sub.setForeground(new java.awt.Color(102, 102, 102));
        btn_sub.setText("Submit");
        btn_sub.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_sub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jButton1.setText("Batal");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 100, 30));

        txt_pnerbit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt_pnerbit.setBorder(new javax.swing.border.MatteBorder(null));
        txt_pnerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pnerbitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pnerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 480, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/upload.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 610));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jdlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jdlActionPerformed

    private void txt_pnerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pnerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pnerbitActionPerformed

    private void txt_jdlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jdlFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jdlFocusGained

    private void txt_thnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thnActionPerformed

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        if (txt_prg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks Pengarang harap diisi.");
        } else if (txt_jdl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks Judul harap diisi.");
        } else if (txt_thn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks Tahun harap diisi.");
        } else if (txt_pnerbit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks Penerbit harap diisi.");
        } else if (txt_topik.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks Topik harap diisi.");
        } else if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Teks User Id harap diisi.");
        } else {
        try {
            String sql = "insert into data_jurnal values ('"+txt_noJurnal.getText()+"','"+txt_prg.getText()+"','"+txt_jdl.getText()+"','"+txt_thn.getText()+"','"+txt_pnerbit.getText()+"','"+txt_topik.getText()+"','"+txtId.getText()+"')";
            java.sql.Connection c = Koneksi.getKoneksi();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Jurnal berhasil disubmit!");
            clearForm();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_subActionPerformed

    private void txt_noJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noJurnalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noJurnalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        masuk a = new masuk(jLabel1.getText());
        a.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upjurnal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_sub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txt_jdl;
    private javax.swing.JTextField txt_noJurnal;
    private javax.swing.JTextField txt_pnerbit;
    private javax.swing.JTextField txt_prg;
    private javax.swing.JTextField txt_thn;
    private javax.swing.JTextField txt_topik;
    // End of variables declaration//GEN-END:variables
}
